apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-concert-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-concert-app
  template:
    metadata:
      labels:
        app: my-concert-app
    spec:
      containers:
      - name: my-concert-app
        image: palonsoacr.azurecr.io/my-concert-app:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "10.0.2.4"  
        - name: DB_USER
          value: "pilar"
        - name: DB_PASSWORD
          value: "pilar"
        - name: DB_NAME
          value: "concierto"
      imagePullSecrets:
      - name: regcred
